create or replace TABLE VIN.DECODE.MAKE_MODEL_VDS (
	MAKE_ID NUMBER(3,0),
	MODEL_ID NUMBER(6,0),
	MODEL_NAME VARCHAR(50),
	VDS VARCHAR(5),
	DESC1 VARCHAR(25),
	DESC2 VARCHAR(25),
	DESC3 VARCHAR(50),
	DESC4 VARCHAR(25),
	DESC5 VARCHAR(25),
	BODY_STYLE VARCHAR(25),
	ENGINE VARCHAR(100),
	DRIVE_TYPE VARCHAR(50),
	TRANSMISSION VARCHAR(50),
	MPG VARCHAR(25)
);